enum types {
  PLANT_WATER_BY_ID_REQUESTED = 'PLANT/WATER_BY_ID_REQUESTED',
  PLANT_WATER_BY_ID_SUCCEEDED = 'PLANT/WATER_BY_ID_SUCCEEDED',
  PLANT_API_FAILED = 'PLANT/API_FAILED',
}

export default types;
