enum types {
    USER_SET_TOKEN = 'USER/USER_SET_TOKEN',
    USER_CREATE_REQUESTED = 'USER/USER_CREATE_REQUESTED',
    USER_FETCH_BY_TOKEN_REQUESTED = 'USER/USER_FETCH_BY_TOKEN_REQUESTED',
    USER_SET_USER = 'USER/USER_SET_USER',
    USER_FETCH_BY_ID_REQUESTED = 'USER/USER_FETCH_BY_ID_REQUESTED',
}

export default types;