enum types {
  PLANTS_WATER_BY_IDS_REQUESTED = 'PLANTS/WATER_BY_IDS_REQUESTED',
  PLANTS_CREATE_ONE_REQUESTED = 'PLANTS/CREATE_ONE_REQUESTED',
  PLANTS_UPDATE_ONE_REQUESTED = 'PLANTS/UPDATE_ONE_REQUESTED',
}

export default types;