enum types {
  HABITATS_FETCH_BY_IDS_REQUESTED = 'HABITATS/FETCH_BY_IDS_REQUESTED',
  SET_HABITATS = 'HABITATS/SET_HABITATS',
  HABITATS_FETCH_USER_SUBSCRIBED_REQUESTED = 'HABITATS/FETCH_USER_SUBSCRIBED_REQUESTED',
  HABITATS_CREATE_ONE_REQUESTED = 'HABITATS/CREATE_ONE_REQUESTED',
  HABITATS_CREATE_ONE_SUCCEEDED = 'HABITATS/CREATE_ONE_SUCCEEDED',
  HABITATS_SEARCH_REQUESTED = 'HABITATS/SEARCH_REQUESTED',
  HABITATS_SET_QUERIED_HABITATS = 'HABITATS/SET_QUERIED_HABITATS',
  HABITATS_REQUEST_SUBSCRIPTION_REQUESTED = 'HABITATS/REQUEST_SUBSCRIPTION_REQUESTED',
  HABITATS_REQUEST_SUBSCRIPTION_SUCCEEDED = 'HABITATS/REQUEST_SUBSCRIPTION_SUCCEEDED',
}

export default types;