enum types {
  HABITATS_FETCH_BY_IDS_REQUESTED = 'HABITATS/FETCH_BY_IDS_REQUESTED',
  SET_HABITATS = 'HABITATS/SET_HABITATS',
  HABITATS_FETCH_USER_SUBSCRIBED_REQUESTED = 'HABITATS/FETCH_USER_SUBSCRIBED_REQUESTED',
  HABITATS_CREATE_ONE_REQUESTED = 'HABITATS/CREATE_ONE_REQUESTED',
  HABITATS_CREATE_ONE_SUCCEEDED = 'HABITATS/CREATE_ONE_SUCCEEDED',
}

export default types;