enum types {
  HABITATS_FETCH_BY_IDS_REQUESTED = 'HABITATS/FETCH_BY_IDS_REQUESTED',
  SET_HABITATS = 'HABITATS/SET_HABITATS',
  HABITATS_FETCH_USER_SUBSCRIBED_REQUESTED = 'HABITATS/HABITATS_FETCH_USER_SUBSCRIBED_REQUESTED',
}

export default types;